services:
  - type: web
    name: flask-web
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python rpc_server.py"
    envVars:
      - key: PORT
        value: "5000"
  - type: worker
    name: rabbitmq-consumer
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python consumidor.py"
    envVars:
      - key: AMQP_URL
        value: "amqps://nvoalptz:Dz-R0OIoGpp3-EhJaA4g8gkxSfk5wzC5@woodpecker.rmq.cloudamqp.com/nvoalptz"
